### ISSUE TITLE
Toggle mobile data takes me to data usage screen

### ISSUE THREAD

**Issue by quite** [ultrafunk/NetInfo#5]
Now, on android 5.1.1 (ok, cyanogenmod 12.1), hitting the toggle-mobile-data button in netinfo does not immediatly toggle data, but instead takes me to Data usage screen. There I have to tap mobile data, and then tap OK to confirm and then another tap to get back to the home screen. Is this intentional? Tapping to toggle wifi/mobile data used to be very convenient in Netinfo.

**Comment by ultrafunk** [comment]
On Android 5.x (Lollipop) the Mobile data ON / OFF toggle displays the Data usage screen because Google has removed the Android API used to turn mobile data on & off for all user installed apps: 

https://code.google.com/p/android-developer-preview/issues/detail?id=2103
https://code.google.com/p/android/issues/detail?id=130608
https://code.google.com/p/android/issues/detail?id=81891

**Comment by quite** [comment]
Oh, that's very disappointing.
