### ISSUE TITLE
Spanish translation disappeared

### ISSUE THREAD

**Issue by Roboe** [ultrafunk/NetInfo#6]
Just noted that my contributions have been reverted in some commit, I suppose by accident. The `values-es` folder on `NetInfo_Widget/src/main/res/` is no longer there.

Can you restore it?

**Comment by Roboe** [comment]
Seems like commit ac699ea34bf49dfacfc625b09642bb435572b8db is the one who deleted the `values-es/strings.xml` file.

**Comment by ultrafunk** [comment]
The Spanish translation was not removed by accident, it was removed because it was outdated (several missing strings) and less than 2% of the users were running on a Spanish language version of Android.

If you want to update the translated strings to match the latest version I will add it back in the next release.

**Comment by Roboe** [comment]
I supposed they were removed accidentaly because removing a volunteer collaboration without even notify the author is not really polite. Please, don't do that again, it feels bad.

I'll update the strings when I have some free time.

**Comment by ultrafunk** [comment]
I understand, but this is a spare time only project for me and I don't have the time or resources available to keep track of all changes and contributions across all development projects I work on. I'm very grateful for all contributions, but sometimes things like these are bound to happen, sorry...

I also tried to contact you about the outdated translation, but I was unable to find any way to reach you.
